# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler

jobs:
  build:
    steps:
      - checkout
      - configure_bundler

  rubocop:
    steps:
      - checkout
      - configure_bundler
      - run:
          name: Rubocop
          command: bundle exec rubocop -A

workflows:
  version: 2.1
  build-and-rubocop:
    jobs:
      - build
      # - rubocop
